name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        satysfi-version:
          - 0.0.6
          - 0.0.7
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:${{ matrix.satysfi-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run opam lint
        run: opam lint
      - name: Pin opam packages
        run: |
          export HOME=/root
          opam pin add -v "file://$PWD"
      - name: Run satyrographos lint
        # satyrographos lint for v0.0.6 is only available with amutake/satysfi:0.0.7
        run: |
          export HOME=/root
          opam exec -- satyrographos lint --satysfi-version 0.0.6
        if: ${{ matrix.satysfi-version == '0.0.7' }}